### ISSUE TITLE
Where can I test this data ?

### ISSUE THREAD

**Issue by Gatsby23** [sachu92/explicit-to-implicit-3d#1]
Hello, I'm impressed by this algorithm implementation, but are there some test data I can download and test it ?

**Comment by sachu92** [comment]
Hi! At the moment, the only input data format it works on is VTK PolyData with a normal vectors at each vertex specified as a PointData. I wrote it to convert explicit surfaces in my simulations to an implicit representation. I have uploaded a test data file to the repo now. For this sample data set, the spatial extent is between -25 and 25 on all three coordinates. Hope that helps.

**Comment by sachu92** [comment]
The direct link to the file : [Download](https://raw.githubusercontent.com/sachu92/explicit-to-implicit-3d/master/test_data.vtp)
